# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_permission_management_python_sdk import schemas  # noqa: F401


class AdminCapabilityConfigDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            allCapabilitiesAccess = schemas.BoolSchema
        
            @staticmethod
            def capabilities() -> typing.Type['AdminCapabilityConfigDTOCapabilities']:
                return AdminCapabilityConfigDTOCapabilities
            __annotations__ = {
                "allCapabilitiesAccess": allCapabilitiesAccess,
                "capabilities": capabilities,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["allCapabilitiesAccess"]) -> MetaOapg.properties.allCapabilitiesAccess: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["capabilities"]) -> 'AdminCapabilityConfigDTOCapabilities': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["allCapabilitiesAccess", "capabilities", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["allCapabilitiesAccess"]) -> typing.Union[MetaOapg.properties.allCapabilitiesAccess, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["capabilities"]) -> typing.Union['AdminCapabilityConfigDTOCapabilities', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["allCapabilitiesAccess", "capabilities", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        allCapabilitiesAccess: typing.Union[MetaOapg.properties.allCapabilitiesAccess, bool, schemas.Unset] = schemas.unset,
        capabilities: typing.Union['AdminCapabilityConfigDTOCapabilities', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AdminCapabilityConfigDTO':
        return super().__new__(
            cls,
            *args,
            allCapabilitiesAccess=allCapabilitiesAccess,
            capabilities=capabilities,
            _configuration=_configuration,
            **kwargs,
        )

from visier_permission_management_python_sdk.model.admin_capability_config_dto_capabilities import AdminCapabilityConfigDTOCapabilities
