# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_permission_management_python_sdk import schemas  # noqa: F401


class DimensionFilterDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def staticDimensionFilter() -> typing.Type['StaticDimensionFilterDTO']:
                return StaticDimensionFilterDTO
        
            @staticmethod
            def dynamicDimensionFilter() -> typing.Type['DynamicDimensionFilterDTO']:
                return DynamicDimensionFilterDTO
            __annotations__ = {
                "staticDimensionFilter": staticDimensionFilter,
                "dynamicDimensionFilter": dynamicDimensionFilter,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["staticDimensionFilter"]) -> 'StaticDimensionFilterDTO': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dynamicDimensionFilter"]) -> 'DynamicDimensionFilterDTO': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["staticDimensionFilter", "dynamicDimensionFilter", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["staticDimensionFilter"]) -> typing.Union['StaticDimensionFilterDTO', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dynamicDimensionFilter"]) -> typing.Union['DynamicDimensionFilterDTO', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["staticDimensionFilter", "dynamicDimensionFilter", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        staticDimensionFilter: typing.Union['StaticDimensionFilterDTO', schemas.Unset] = schemas.unset,
        dynamicDimensionFilter: typing.Union['DynamicDimensionFilterDTO', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DimensionFilterDTO':
        return super().__new__(
            cls,
            *args,
            staticDimensionFilter=staticDimensionFilter,
            dynamicDimensionFilter=dynamicDimensionFilter,
            _configuration=_configuration,
            **kwargs,
        )

from visier_permission_management_python_sdk.model.dynamic_dimension_filter_dto import DynamicDimensionFilterDTO
from visier_permission_management_python_sdk.model.static_dimension_filter_dto import StaticDimensionFilterDTO
