# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_permission_management_python_sdk import schemas  # noqa: F401


class GetContentPackagesAPIResponseDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            
            
            class contentPackages(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ContentPackageDTO']:
                        return ContentPackageDTO
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ContentPackageDTO'], typing.List['ContentPackageDTO']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'contentPackages':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ContentPackageDTO':
                    return super().__getitem__(i)
            __annotations__ = {
                "contentPackages": contentPackages,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["contentPackages"]) -> MetaOapg.properties.contentPackages: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["contentPackages", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["contentPackages"]) -> typing.Union[MetaOapg.properties.contentPackages, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["contentPackages", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        contentPackages: typing.Union[MetaOapg.properties.contentPackages, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'GetContentPackagesAPIResponseDTO':
        return super().__new__(
            cls,
            *args,
            contentPackages=contentPackages,
            _configuration=_configuration,
            **kwargs,
        )

from visier_permission_management_python_sdk.model.content_package_dto import ContentPackageDTO
