# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_permission_management_python_sdk import schemas  # noqa: F401


class InheritedAccessConfigDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            analyticObjectId = schemas.StrSchema
            removeAccess = schemas.BoolSchema
            
            
            class memberFilterConfigs(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['MemberFilterConfigDTO']:
                        return MemberFilterConfigDTO
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['MemberFilterConfigDTO'], typing.List['MemberFilterConfigDTO']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'memberFilterConfigs':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'MemberFilterConfigDTO':
                    return super().__getitem__(i)
            __annotations__ = {
                "analyticObjectId": analyticObjectId,
                "removeAccess": removeAccess,
                "memberFilterConfigs": memberFilterConfigs,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["analyticObjectId"]) -> MetaOapg.properties.analyticObjectId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["removeAccess"]) -> MetaOapg.properties.removeAccess: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["memberFilterConfigs"]) -> MetaOapg.properties.memberFilterConfigs: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["analyticObjectId", "removeAccess", "memberFilterConfigs", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["analyticObjectId"]) -> typing.Union[MetaOapg.properties.analyticObjectId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["removeAccess"]) -> typing.Union[MetaOapg.properties.removeAccess, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["memberFilterConfigs"]) -> typing.Union[MetaOapg.properties.memberFilterConfigs, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["analyticObjectId", "removeAccess", "memberFilterConfigs", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        analyticObjectId: typing.Union[MetaOapg.properties.analyticObjectId, str, schemas.Unset] = schemas.unset,
        removeAccess: typing.Union[MetaOapg.properties.removeAccess, bool, schemas.Unset] = schemas.unset,
        memberFilterConfigs: typing.Union[MetaOapg.properties.memberFilterConfigs, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'InheritedAccessConfigDTO':
        return super().__new__(
            cls,
            *args,
            analyticObjectId=analyticObjectId,
            removeAccess=removeAccess,
            memberFilterConfigs=memberFilterConfigs,
            _configuration=_configuration,
            **kwargs,
        )

from visier_permission_management_python_sdk.model.member_filter_config_dto import MemberFilterConfigDTO
