# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_permission_management_python_sdk import schemas  # noqa: F401


class MemberSelectionDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def namePath() -> typing.Type['MemberSelectionDTONamePath']:
                return MemberSelectionDTONamePath
            excluded = schemas.BoolSchema
            __annotations__ = {
                "namePath": namePath,
                "excluded": excluded,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["namePath"]) -> 'MemberSelectionDTONamePath': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["excluded"]) -> MetaOapg.properties.excluded: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["namePath", "excluded", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["namePath"]) -> typing.Union['MemberSelectionDTONamePath', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["excluded"]) -> typing.Union[MetaOapg.properties.excluded, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["namePath", "excluded", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        namePath: typing.Union['MemberSelectionDTONamePath', schemas.Unset] = schemas.unset,
        excluded: typing.Union[MetaOapg.properties.excluded, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'MemberSelectionDTO':
        return super().__new__(
            cls,
            *args,
            namePath=namePath,
            excluded=excluded,
            _configuration=_configuration,
            **kwargs,
        )

from visier_permission_management_python_sdk.model.member_selection_dto_name_path import MemberSelectionDTONamePath
