# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_permission_management_python_sdk import schemas  # noqa: F401


class SecurableDimensionDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            dimensionId = schemas.StrSchema
            displayName = schemas.StrSchema
        
            @staticmethod
            def analyticObjectIds() -> typing.Type['SecurableDimensionDTOAnalyticObjectIds']:
                return SecurableDimensionDTOAnalyticObjectIds
            
            
            class hierarchyProperties(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['HierarchyPropertyDTO']:
                        return HierarchyPropertyDTO
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['HierarchyPropertyDTO'], typing.List['HierarchyPropertyDTO']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'hierarchyProperties':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'HierarchyPropertyDTO':
                    return super().__getitem__(i)
            __annotations__ = {
                "dimensionId": dimensionId,
                "displayName": displayName,
                "analyticObjectIds": analyticObjectIds,
                "hierarchyProperties": hierarchyProperties,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dimensionId"]) -> MetaOapg.properties.dimensionId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["displayName"]) -> MetaOapg.properties.displayName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["analyticObjectIds"]) -> 'SecurableDimensionDTOAnalyticObjectIds': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["hierarchyProperties"]) -> MetaOapg.properties.hierarchyProperties: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["dimensionId", "displayName", "analyticObjectIds", "hierarchyProperties", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dimensionId"]) -> typing.Union[MetaOapg.properties.dimensionId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["displayName"]) -> typing.Union[MetaOapg.properties.displayName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["analyticObjectIds"]) -> typing.Union['SecurableDimensionDTOAnalyticObjectIds', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["hierarchyProperties"]) -> typing.Union[MetaOapg.properties.hierarchyProperties, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["dimensionId", "displayName", "analyticObjectIds", "hierarchyProperties", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        dimensionId: typing.Union[MetaOapg.properties.dimensionId, str, schemas.Unset] = schemas.unset,
        displayName: typing.Union[MetaOapg.properties.displayName, str, schemas.Unset] = schemas.unset,
        analyticObjectIds: typing.Union['SecurableDimensionDTOAnalyticObjectIds', schemas.Unset] = schemas.unset,
        hierarchyProperties: typing.Union[MetaOapg.properties.hierarchyProperties, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SecurableDimensionDTO':
        return super().__new__(
            cls,
            *args,
            dimensionId=dimensionId,
            displayName=displayName,
            analyticObjectIds=analyticObjectIds,
            hierarchyProperties=hierarchyProperties,
            _configuration=_configuration,
            **kwargs,
        )

from visier_permission_management_python_sdk.model.hierarchy_property_dto import HierarchyPropertyDTO
from visier_permission_management_python_sdk.model.securable_dimension_dto_analytic_object_ids import SecurableDimensionDTOAnalyticObjectIds
