# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_permission_management_python_sdk
from visier_permission_management_python_sdk.model.role_modules_config_dto_content_package_ids import RoleModulesConfigDTOContentPackageIds
from visier_permission_management_python_sdk import configuration


class TestRoleModulesConfigDTOContentPackageIds(unittest.TestCase):
    """RoleModulesConfigDTOContentPackageIds unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
