# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_permission_management_python_sdk
from visier_permission_management_python_sdk.model.get_capabilities_api_response_dto import GetCapabilitiesAPIResponseDTO
from visier_permission_management_python_sdk import configuration


class TestGetCapabilitiesAPIResponseDTO(unittest.TestCase):
    """GetCapabilitiesAPIResponseDTO unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
