# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_permission_management_python_sdk
from visier_permission_management_python_sdk.model.admin_capability_config_dto_capabilities import AdminCapabilityConfigDTOCapabilities
from visier_permission_management_python_sdk import configuration


class TestAdminCapabilityConfigDTOCapabilities(unittest.TestCase):
    """AdminCapabilityConfigDTOCapabilities unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
