# coding: utf-8
"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from visier_permission_management_python_sdk.client_custom import ClientCustom
from visier_permission_management_python_sdk.configuration import Configuration
from visier_permission_management_python_sdk.api_client import ApiClient
from visier_permission_management_python_sdk.type_util import copy_signature
from visier_permission_management_python_sdk.apis.tags.permission_management_api import PermissionManagementApi



class VisierPermissionManagement(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.permission_management: PermissionManagementApi = PermissionManagementApi(api_client)
