# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class CapabilityDTO(BaseModel):
    # A description of the capability.
    description: typing.Optional[str] = Field(None, alias='description')

    # The unique name of the capability.
    name: typing.Optional[str] = Field(None, alias='name')

    # An identifiable capability name to display in Visier, such as \"Schedule Analysis\".
    display_name: typing.Optional[str] = Field(None, alias='displayName')
    class Config:
        arbitrary_types_allowed = True
