# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_permission_management_python_sdk.pydantic.dynamic_dimension_filter_dto import DynamicDimensionFilterDTO
from visier_permission_management_python_sdk.pydantic.static_dimension_filter_dto import StaticDimensionFilterDTO

class DimensionFilterDTO(BaseModel):
    static_dimension_filter: typing.Optional[StaticDimensionFilterDTO] = Field(None, alias='staticDimensionFilter')

    dynamic_dimension_filter: typing.Optional[DynamicDimensionFilterDTO] = Field(None, alias='dynamicDimensionFilter')
    class Config:
        arbitrary_types_allowed = True
