# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_permission_management_python_sdk.pydantic.member_filter_config_dto import MemberFilterConfigDTO

class InheritedAccessConfigDTO(BaseModel):
    # The analytic object ID associated with the inherited access configuration.
    analytic_object_id: typing.Optional[str] = Field(None, alias='analyticObjectId')

    # The flag for removing access to the inherited analytic object.
    remove_access: typing.Optional[bool] = Field(None, alias='removeAccess')

    # The member filter configurations that defines the population in the inherited analytic object.
    member_filter_configs: typing.Optional[typing.List[MemberFilterConfigDTO]] = Field(None, alias='memberFilterConfigs')
    class Config:
        arbitrary_types_allowed = True
