# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_permission_management_python_sdk.pydantic.member_selection_dto_name_path import MemberSelectionDTONamePath

class MemberSelectionDTO(BaseModel):
    name_path: typing.Optional[MemberSelectionDTONamePath] = Field(None, alias='namePath')

    # The flag for excluding the member.
    excluded: typing.Optional[bool] = Field(None, alias='excluded')
    class Config:
        arbitrary_types_allowed = True
