# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_permission_management_python_sdk.pydantic.permission_failure_dto import PermissionFailureDTO
from visier_permission_management_python_sdk.pydantic.permission_success_dto import PermissionSuccessDTO

class PermissionBulkOperationResponseDTO(BaseModel):
    # The successfully processed permissions.
    successes: typing.Optional[typing.List[PermissionSuccessDTO]] = Field(None, alias='successes')

    # The permissions that did not process and any relevant error information.
    failures: typing.Optional[typing.List[PermissionFailureDTO]] = Field(None, alias='failures')
    class Config:
        arbitrary_types_allowed = True
