# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class PermissionErrorDTO(BaseModel):
    # Error message
    message: typing.Optional[str] = Field(None, alias='message')

    # A root cause identifier that allows Visier to determine the source of the problem.
    rci: typing.Optional[str] = Field(None, alias='rci')
    class Config:
        arbitrary_types_allowed = True
