# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_permission_management_python_sdk.pydantic.role_modules_config_dto_content_package_ids import RoleModulesConfigDTOContentPackageIds

class RoleModulesConfigDTO(BaseModel):
    content_package_ids: typing.Optional[RoleModulesConfigDTOContentPackageIds] = Field(None, alias='contentPackageIds')
    class Config:
        arbitrary_types_allowed = True
