# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class SecurablePropertyDTO(BaseModel):
    # The property ID.
    property_id: typing.Optional[str] = Field(None, alias='propertyId')

    # An identifiable property name to display in Visier, such as \"Job Pay Level\".
    display_name: typing.Optional[str] = Field(None, alias='displayName')

    # The property's analytic object ID.
    analytic_object_id: typing.Optional[str] = Field(None, alias='analyticObjectId')

    # If true, this property is the analytic object's primary key.
    is_primary_key: typing.Optional[bool] = Field(None, alias='isPrimaryKey')

    # The reference symbol name.
    reference_symbol_name: typing.Optional[str] = Field(None, alias='referenceSymbolName')
    class Config:
        arbitrary_types_allowed = True
