# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_permission_management_python_sdk.pydantic.member_selection_dto import MemberSelectionDTO
from visier_permission_management_python_sdk.pydantic.static_dimension_filter_dto_subject_reference_path import StaticDimensionFilterDTOSubjectReferencePath

class StaticDimensionFilterDTO(BaseModel):
    # The dimension ID associated with the static dimension filter.
    dimension_id: typing.Optional[str] = Field(None, alias='dimensionId')

    subject_reference_path: typing.Optional[StaticDimensionFilterDTOSubjectReferencePath] = Field(None, alias='subjectReferencePath')

    # A list of objects representing the member selections associated with the static dimension filter.
    member_selections: typing.Optional[typing.List[MemberSelectionDTO]] = Field(None, alias='memberSelections')
    class Config:
        arbitrary_types_allowed = True
