# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_permission_management_python_sdk.paths.v1_admin_permissions.post import CreatePermissions
from visier_permission_management_python_sdk.paths.v1_admin_permissions.delete import DeletePermissions
from visier_permission_management_python_sdk.paths.v1_admin_capabilities.get import GetCapabilities
from visier_permission_management_python_sdk.paths.v1_admin_capabilities_capability_id.get import GetCapability
from visier_permission_management_python_sdk.paths.v1_admin_content_packages_content_package_id.get import GetContentPackage
from visier_permission_management_python_sdk.paths.v1_admin_content_packages.get import GetContentPackages
from visier_permission_management_python_sdk.paths.v1_admin_data_security_objects.get import GetDataSecurityObjects
from visier_permission_management_python_sdk.paths.v1_admin_permissions_permission_id.get import GetPermission
from visier_permission_management_python_sdk.paths.v1_admin_permissions.get import GetPermissions
from visier_permission_management_python_sdk.paths.v1_admin_permissions.put import UpdatePermissions
from visier_permission_management_python_sdk.apis.tags.permission_management_api_raw import PermissionManagementApiRaw


class PermissionManagementApi(
    CreatePermissions,
    DeletePermissions,
    GetCapabilities,
    GetCapability,
    GetContentPackage,
    GetContentPackages,
    GetDataSecurityObjects,
    GetPermission,
    GetPermissions,
    UpdatePermissions,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PermissionManagementApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PermissionManagementApiRaw(api_client)
