# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_permission_management_python_sdk.type.admin_capability_config_dto_capabilities import AdminCapabilityConfigDTOCapabilities

class RequiredAdminCapabilityConfigDTO(TypedDict):
    pass

class OptionalAdminCapabilityConfigDTO(TypedDict, total=False):
    # If true, this capability configuration grant access to all capabilities.
    allCapabilitiesAccess: bool

    capabilities: AdminCapabilityConfigDTOCapabilities

class AdminCapabilityConfigDTO(RequiredAdminCapabilityConfigDTO, OptionalAdminCapabilityConfigDTO):
    pass
