# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCapabilityDTO(TypedDict):
    pass

class OptionalCapabilityDTO(TypedDict, total=False):
    # A description of the capability.
    description: str

    # The unique name of the capability.
    name: str

    # An identifiable capability name to display in Visier, such as \"Schedule Analysis\".
    displayName: str

class CapabilityDTO(RequiredCapabilityDTO, OptionalCapabilityDTO):
    pass
