# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_permission_management_python_sdk.type.inherited_access_config_dto import InheritedAccessConfigDTO
from visier_permission_management_python_sdk.type.member_filter_config_dto import MemberFilterConfigDTO
from visier_permission_management_python_sdk.type.property_set_config_dto import PropertySetConfigDTO

class RequiredDataSecurityProfileDTO(TypedDict):
    pass

class OptionalDataSecurityProfileDTO(TypedDict, total=False):
    # The analytic object ID associated with the data security profile.
    analyticObjectId: str

    # The property set configuration that defines which properties and access level to allow for each filtered record.
    propertySetConfig: PropertySetConfigDTO

    # The flag for giving all access to data points when creating a population.
    allDataPointAccess: bool

    # The member filter configurations that defines the population.
    memberFilterConfigs: typing.List[MemberFilterConfigDTO]

    # A list of objects representing the inherited access configurations associated with the data security profile.  By default all related objects of a top level analytic object will inherit access.  To remove access to a related analytic object, add it to the list of inherited access configurations with removeAccess: true.  To add custom filters to a related analytic object, add the analytic object to the list of inherited access configurations and then add the custom filters to its list of member filter configurations.
    inheritedAccessConfigs: typing.List[InheritedAccessConfigDTO]

class DataSecurityProfileDTO(RequiredDataSecurityProfileDTO, OptionalDataSecurityProfileDTO):
    pass
