# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_permission_management_python_sdk.type.dynamic_dimension_filter_dto import DynamicDimensionFilterDTO
from visier_permission_management_python_sdk.type.static_dimension_filter_dto import StaticDimensionFilterDTO

class RequiredDimensionFilterDTO(TypedDict):
    pass

class OptionalDimensionFilterDTO(TypedDict, total=False):
    staticDimensionFilter: StaticDimensionFilterDTO

    dynamicDimensionFilter: DynamicDimensionFilterDTO

class DimensionFilterDTO(RequiredDimensionFilterDTO, OptionalDimensionFilterDTO):
    pass
