# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_permission_management_python_sdk.type.user_property_dto import UserPropertyDTO

class RequiredDynamicPropertyMappingDTO(TypedDict):
    pass

class OptionalDynamicPropertyMappingDTO(TypedDict, total=False):
    # The hierarchy property ID.
    hierarchyPropertyId: str

    # The user property.
    userProperty: UserPropertyDTO

class DynamicPropertyMappingDTO(RequiredDynamicPropertyMappingDTO, OptionalDynamicPropertyMappingDTO):
    pass
