# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_permission_management_python_sdk.type.dynamic_dimension_filter_dto_subject_reference_path import DynamicDimensionFilterDTOSubjectReferencePath
from visier_permission_management_python_sdk.type.dynamic_property_mapping_dto import DynamicPropertyMappingDTO

class RequiredDynamicDimensionFilterDTO(TypedDict):
    pass

class OptionalDynamicDimensionFilterDTO(TypedDict, total=False):
    # The dimension ID associated with the dynamic dimension filter.
    dimensionId: str

    subjectReferencePath: DynamicDimensionFilterDTOSubjectReferencePath

    # A list of objects representing the dynamic property mappings associated with the dynamic dimension filter.
    dynamicPropertyMappings: typing.List[DynamicPropertyMappingDTO]

class DynamicDimensionFilterDTO(RequiredDynamicDimensionFilterDTO, OptionalDynamicDimensionFilterDTO):
    pass
