# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_permission_management_python_sdk.type.content_package_dto import ContentPackageDTO

class RequiredGetContentPackagesAPIResponseDTO(TypedDict):
    pass

class OptionalGetContentPackagesAPIResponseDTO(TypedDict, total=False):
    # A list of objects representing the available content packages.
    contentPackages: typing.List[ContentPackageDTO]

class GetContentPackagesAPIResponseDTO(RequiredGetContentPackagesAPIResponseDTO, OptionalGetContentPackagesAPIResponseDTO):
    pass
