# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_permission_management_python_sdk.type.analytic_object_dto import AnalyticObjectDTO

class RequiredGetDataSecurityObjectsAPIResponseDTO(TypedDict):
    pass

class OptionalGetDataSecurityObjectsAPIResponseDTO(TypedDict, total=False):
    # A list of analytic objects and their related objects that are available to define data access to.
    analyticObjects: typing.List[AnalyticObjectDTO]

class GetDataSecurityObjectsAPIResponseDTO(RequiredGetDataSecurityObjectsAPIResponseDTO, OptionalGetDataSecurityObjectsAPIResponseDTO):
    pass
