# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredHierarchyPropertyDTO(TypedDict):
    pass

class OptionalHierarchyPropertyDTO(TypedDict, total=False):
    # The hierarchy property ID.
    hierarchyPropertyId: str

    # An identifiable hierarchy property name to display in Visier, such as \"Name Property\".
    displayName: str

class HierarchyPropertyDTO(RequiredHierarchyPropertyDTO, OptionalHierarchyPropertyDTO):
    pass
