# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_permission_management_python_sdk.type.member_filter_config_dto import MemberFilterConfigDTO

class RequiredInheritedAccessConfigDTO(TypedDict):
    pass

class OptionalInheritedAccessConfigDTO(TypedDict, total=False):
    # The analytic object ID associated with the inherited access configuration.
    analyticObjectId: str

    # The flag for removing access to the inherited analytic object.
    removeAccess: bool

    # The member filter configurations that defines the population in the inherited analytic object.
    memberFilterConfigs: typing.List[MemberFilterConfigDTO]

class InheritedAccessConfigDTO(RequiredInheritedAccessConfigDTO, OptionalInheritedAccessConfigDTO):
    pass
