# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_permission_management_python_sdk.type.member_selection_dto_name_path import MemberSelectionDTONamePath

class RequiredMemberSelectionDTO(TypedDict):
    pass

class OptionalMemberSelectionDTO(TypedDict, total=False):
    namePath: MemberSelectionDTONamePath

    # The flag for excluding the member.
    excluded: bool

class MemberSelectionDTO(RequiredMemberSelectionDTO, OptionalMemberSelectionDTO):
    pass
