# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_permission_management_python_sdk.type.permission_failure_dto import PermissionFailureDTO
from visier_permission_management_python_sdk.type.permission_success_dto import PermissionSuccessDTO

class RequiredPermissionBulkOperationResponseDTO(TypedDict):
    pass

class OptionalPermissionBulkOperationResponseDTO(TypedDict, total=False):
    # The successfully processed permissions.
    successes: typing.List[PermissionSuccessDTO]

    # The permissions that did not process and any relevant error information.
    failures: typing.List[PermissionFailureDTO]

class PermissionBulkOperationResponseDTO(RequiredPermissionBulkOperationResponseDTO, OptionalPermissionBulkOperationResponseDTO):
    pass
