# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_permission_management_python_sdk.type.admin_capability_config_dto import AdminCapabilityConfigDTO
from visier_permission_management_python_sdk.type.data_security_profile_dto import DataSecurityProfileDTO
from visier_permission_management_python_sdk.type.role_modules_config_dto import RoleModulesConfigDTO

class RequiredPermissionDTO(TypedDict):
    pass

class OptionalPermissionDTO(TypedDict, total=False):
    # A user-defined description of the permission.
    description: str

    # The unique identifier associated with the permission.
    permissionId: str

    # An identifiable permission name to display in Visier, such as \"Diversity Access\".
    displayName: str

    # A list of objects representing the data security profile configurations associated with the permission.
    dataSecurityProfiles: typing.List[DataSecurityProfileDTO]

    # The capability configuration associated with the permission.
    adminCapabilityConfig: AdminCapabilityConfigDTO

    # The role modules configuration associated with the permission.
    roleModulesConfig: RoleModulesConfigDTO

class PermissionDTO(RequiredPermissionDTO, OptionalPermissionDTO):
    pass
