# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_permission_management_python_sdk.type.permission_dto import PermissionDTO

class RequiredPermissionsListDTO(TypedDict):
    pass

class OptionalPermissionsListDTO(TypedDict, total=False):
    # The list of permissions that will be created or updated
    permissions: typing.List[PermissionDTO]

class PermissionsListDTO(RequiredPermissionsListDTO, OptionalPermissionsListDTO):
    pass
