# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPermissionErrorDTO(TypedDict):
    pass

class OptionalPermissionErrorDTO(TypedDict, total=False):
    # Error message
    message: str

    # A root cause identifier that allows Visier to determine the source of the problem.
    rci: str

class PermissionErrorDTO(RequiredPermissionErrorDTO, OptionalPermissionErrorDTO):
    pass
