# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredSecurablePropertyDTO(TypedDict):
    pass

class OptionalSecurablePropertyDTO(TypedDict, total=False):
    # The property ID.
    propertyId: str

    # An identifiable property name to display in Visier, such as \"Job Pay Level\".
    displayName: str

    # The property's analytic object ID.
    analyticObjectId: str

    # If true, this property is the analytic object's primary key.
    isPrimaryKey: bool

    # The reference symbol name.
    referenceSymbolName: str

class SecurablePropertyDTO(RequiredSecurablePropertyDTO, OptionalSecurablePropertyDTO):
    pass
