# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_permission_management_python_sdk.type.hierarchy_property_dto import HierarchyPropertyDTO
from visier_permission_management_python_sdk.type.securable_dimension_dto_analytic_object_ids import SecurableDimensionDTOAnalyticObjectIds

class RequiredSecurableDimensionDTO(TypedDict):
    pass

class OptionalSecurableDimensionDTO(TypedDict, total=False):
    # The dimension ID.
    dimensionId: str

    # An identifiable dimension name to display in Visier, such as \"Contract Type\".
    displayName: str

    analyticObjectIds: SecurableDimensionDTOAnalyticObjectIds

    # The list of hierarchies you can map to a user in a permission's dynamic filter.
    hierarchyProperties: typing.List[HierarchyPropertyDTO]

class SecurableDimensionDTO(RequiredSecurableDimensionDTO, OptionalSecurableDimensionDTO):
    pass
