# coding: utf-8

"""
    Visier Permission Management APIs

    Visier APIs for managing permissions within an organization

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_permission_management_python_sdk.type.member_selection_dto import MemberSelectionDTO
from visier_permission_management_python_sdk.type.static_dimension_filter_dto_subject_reference_path import StaticDimensionFilterDTOSubjectReferencePath

class RequiredStaticDimensionFilterDTO(TypedDict):
    pass

class OptionalStaticDimensionFilterDTO(TypedDict, total=False):
    # The dimension ID associated with the static dimension filter.
    dimensionId: str

    subjectReferencePath: StaticDimensionFilterDTOSubjectReferencePath

    # A list of objects representing the member selections associated with the static dimension filter.
    memberSelections: typing.List[MemberSelectionDTO]

class StaticDimensionFilterDTO(RequiredStaticDimensionFilterDTO, OptionalStaticDimensionFilterDTO):
    pass
